name: project
description: Drop Number 2048 is amazing number games ! So Merge number block & number stack.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.8.8+10808

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appsflyer_sdk: ^6.4.0+2
  confetti: ^0.7.0
  cupertino_icons: ^1.0.5
  device_info: ^2.0.2
  firebase_analytics: ^9.1.10
  firebase_core: ^1.18.0
  firebase_messaging: ^11.4.2
  flame: ^1.1.2
  flame_svg: ^1.3.0
  flutter_local_notifications: ^9.1.5
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.0
  games_services: ^2.0.7
  gameanalytics_sdk: ^1.2.7
  google_mobile_ads: ^1.3.0
  http: ^0.13.4
  in_app_purchase: ^3.0.6
  in_app_review: ^2.0.2
  intl: ^0.17.0
  # package_info_plus: ^1.4.1
  path_provider: ^2.0.8
  screenshot: ^1.2.3
  share: ^2.0.4
  shared_preferences: ^2.0.15
  # smartlook: ^2.0.1
  soundpool: ^2.1.0
  rive: ^0.9.0
  unity_ads_plugin: ^0.3.3
  url_launcher: ^6.1.4
  vibration: ^1.7.4-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - anims/
    - assets/images/
    - assets/sounds/
    - texts/

  fonts:
    - family: quicksand
      fonts:
        - asset: fonts/quicksand-bold.ttf
    - family: icons
      fonts:
        - asset: fonts/myicons.ttf